### ISSUE TITLE
i2c scan - no debug information

### ISSUE THREAD

**Issue by anwarbashir** [nielsnl68/node-red-contrib-i2c#13]
I have connected a device on I2C and with i2cdetect -y 1 the device appears as 57. I assume that the i2c scan node should detect same device. I configured with /dev/i2c-1 and deployed with both defalt address 24 and then 57. In neither case on either output did I receive any scan data. I assumed that on deploy the scan is triggered? If not how do I trigger - do I use an inject node?

**Comment by nielsnl68** [comment]
Hi, can you show the flow?

Op 9 aug. 2017 20:19 schreef "anwarbashir" <notifications@github.com>:

**Comment by anwarbashir** [comment]
Hi, Here is the flow

[{"id":"53939255.99d01c","type":"i2c scan","z":"70881065.70215","i2cdevice":"f5001de1.967ef","name":"test","x":214,"y":143,"wires":[["531f966c.dff9c8"],["102e1f53.788861"]]},{"id":"f5001de1.967ef","type":"i2c-device","z":"","device":"/dev/I2C-1","address":"24"}]

I have also attached an image...
![i2c-scan](https://user-images.githubusercontent.com/8395879/29161141-f7211b22-7dac-11e7-9f54-26787dfb3fb6.PNG)

**Comment by nielsnl68** [comment]
Hi, to us the i2c scan node you need to trigger this node with something like a injection node

I hope this helps
Niels

Sent from Mail for Windows 10

**Comment by anwarbashir** [comment]
Hi, 

Okay this helps, now I send a timestamp to the scan node (note i am using /dev/i2c-1 not /dev/I2C-1, i.e. case sensitive) I am now recieving a debug value. 
However the value of 87 means nothing to me. I do not know what value to place in the address, I can set the default to 24 or 57 with same result. If I use i2cdetect -y 1 from the command line I get 57 (0x57), so I was expecting the same, not 87. Am I misundertanding the objective of your scan node?

**Comment by nielsnl68** [comment]
That is because My nodes are using decimal notations and i2cdetect show
them in hexadecimals.

Op 14 aug. 2017 17:06 schreef "anwarbashir" <notifications@github.com>:

Hi,

Okay this helps, now I send a timestamp to the scan node (note i am using
/dev/i2c-1 not /dev/I2C-1, i.e. case sensitive) I am now recieving a debug
value.
However the value of 87 means nothing to me. I do not know what value to
place in the address, I can set the default to 24 or 57 with same result.
If I use i2cdetect -y 1 from the command line I get 57 (0x57), so I was
expecting the same, not 87. Am I misundertanding the objective of your scan
node?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nielsnl68/node-contrib-i2c/issues/13#issuecomment-322216083>,
or mute the thread

**Comment by anwarbashir** [comment]
Hi Okay, understood and checked. Indeed 87(dec) is 57(hex) so I am receiving the correct value. However can you clarify what value I should place in the address, should it remain as default 24 or some other value?

**Comment by nielsnl68** [comment]
Dont mind using the default value, use the on from the node or send it with the `msg.address`.
BTW. I have upgrade my node modules. please check of your issue still exist.
