### ISSUE TITLE
"TypeError: Failed to set address" 

### ISSUE THREAD

**Issue by shriphoenix** [nielsnl68/node-red-contrib-i2c#14]
Hi @nielsnl68,
I am very much new to node-red and i am trying to access HMC5883L_3-Axis_Digital_Compass_IC using node-contrib-i2c node.

However, i am getting "TypeError: Failed to set address".

Even tried with MPU6050, but same error.

**Script:**

`
[{"id":"add54b54.479528","type":"i2c in","z":"6a0394b0.d8f18c","name":"","i2cdevice":"83bd795d.cdf7e8","address":"30","command":"2","count":"1","x":260,"y":180,"wires":[["85241bfd.ceae98"]]},{"id":"6223d6ec.3a40f8","type":"inject","z":"6a0394b0.d8f18c","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"x":90,"y":180,"wires":[["add54b54.479528"]]},{"id":"85241bfd.ceae98","type":"debug","z":"6a0394b0.d8f18c","name":"","active":true,"console":"false","complete":"false","x":450,"y":180,"wires":[]},{"id":"83bd795d.cdf7e8","type":"i2c-device","z":"","device":"dev/I2C-1","address":"30"}]
`
**Screenshots:**
![1](https://user-images.githubusercontent.com/10812673/29892835-ba713e86-8ded-11e7-913d-5f4c40153a17.jpg)
![2](https://user-images.githubusercontent.com/10812673/29892841-bf3439b4-8ded-11e7-877e-168f345f93ae.jpg)

I am able to access the I2C slave device from terminal using i2cget and i2cset commands.
Please need help, it's bugging me like anything..

Regards,

Shri

**Comment by nielsnl68** [comment]
Yeah there are some issues in the current version.
There will be an update soon.

I am wondering how you plan to talk and initalisate those devices?

The idea is to create some sort of node that can be used to setup and talk
to the device. But still struggling on how the node should work. There are
to many variations posible.



Op 30 aug. 2017 22:15 schreef "shriphoenix" <notifications@github.com>:

Hi @nielsnl68 <https://github.com/nielsnl68>,
I am very much new to node-red and i am trying to access
HMC5883L_3-Axis_Digital_Compass_IC using node-contrib-i2c node.

However, i am getting "TypeError: Failed to set address".

Even tried with MPU6050, but same error.

*Script:*

[{"id":"add54b54.479528","type":"i2c in","z":"6a0394b0.d8f18c","
name":"","i2cdevice":"83bd795d.cdf7e8","address":"
30","command":"2","count":"1","x":260,"y":180,"wires":[["
85241bfd.ceae98"]]},{"id":"6223d6ec.3a40f8","type":"
inject","z":"6a0394b0.d8f18c","name":"","topic":"","payload"
:"true","payloadType":"bool","repeat":"","crontab":"","once"
:false,"x":90,"y":180,"wires":[["add54b54.479528"]]},{"id":"
85241bfd.ceae98","type":"debug","z":"6a0394b0.d8f18c","
name":"","active":true,"console":"false","complete":"
false","x":450,"y":180,"wires":[]},{"id":"83bd795d.cdf7e8","
type":"i2c-device","z":"","device":"dev/I2C-1","address":"30"}]
*Screenshots:*
[image: 1]
<https://user-images.githubusercontent.com/10812673/29892835-ba713e86-8ded-11e7-913d-5f4c40153a17.jpg>
[image: 2]
<https://user-images.githubusercontent.com/10812673/29892841-bf3439b4-8ded-11e7-877e-168f345f93ae.jpg>

I am able to access the I2C slave device from terminal using i2cget and
i2cset commands.
Please need help, it's bugging me like anything..

Regards,

Shri

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nielsnl68/node-contrib-i2c/issues/14>, or mute the
thread

**Comment by clickworkorange** [comment]
First of all, check the permissions on your i2c bus (e.g. `ls -l /dev/i2c-1`) and add your Node-RED user to the correct group (e.g. `adduser nodered i2c`) to grant it access. 

Secondly, i2c addresses and commands are typically hexadecimal values, but the "spinners" on the `address` and `command` fields, as well as their input type being set to "number", prevents one from entering e.g. `0x53`. Personally, I found this confusing, though it's easy enough to perform the conversion. I can poll an ADXL345 accelerometer with the address 83 (0x53) and command 50 (0x32):

![screenshot_2017-09-07_04-57-41](https://user-images.githubusercontent.com/196348/30146018-6ba2d5f8-938d-11e7-92fd-d7483df3a019.png)

**Comment by shriphoenix** [comment]
Hi,
I2C module is perfectly fine and i have written small python script using which i am able to communicate with I2C peripheral successfully. Only using node red it is not working...

**Comment by clickworkorange** [comment]
Did you grant Node-RED access to the i2c bus?

**Comment by nielsnl68** [comment]
I have upgrade my node modules. please check of your issue still exist.

**Comment by shriphoenix** [comment]
I have already grant access to user 'pi'..

However, when i try to grant access to nodered it doesn't recognize.

find below image:
![i2c](https://user-images.githubusercontent.com/10812673/30518884-450e752e-9ba7-11e7-9a9a-bb8f4846d108.JPG)



also will try your new modules....

Thank you...

**Comment by shriphoenix** [comment]
after updating node-red-contrib-i2c crashed entire node-red flow...

not running at all...

![node-red-flow](https://user-images.githubusercontent.com/10812673/30518926-4f06ba72-9ba8-11e7-8ec7-a2934447a822.jpg)
![no-red-console](https://user-images.githubusercontent.com/10812673/30518929-559bc076-9ba8-11e7-8bd9-2ae47c839cd8.jpg)

**Comment by nielsnl68** [comment]
I know, you need to remove the old config node from the configuration
sidebar .

Op 17 sep. 2017 09:38 schreef "shriphoenix" <notifications@github.com>:

**Comment by shriphoenix** [comment]
Hi,
Yes... i did not remove previous nodes.. better if it is mentioned somewhere in github.

Tried with clean install of nodered, i2c node worked like champ..

Thank you for everything...

**Comment by clickworkorange** [comment]
Just for the record: you can see (and change) which user/group Node-RED runs under by looking in `/lib/systemd/system/nodered.service` (if you're running a SystemD based distro).

**Comment by shriphoenix** [comment]
Hi,
user is 'pi', find below screen shot.

![piuser](https://user-images.githubusercontent.com/10812673/30540436-d4331384-9c94-11e7-8299-e526baabcdf9.JPG)

**Comment by clickworkorange** [comment]
Yes, that would be the default on a clean install. However I would recommend that you create a new user for running Node-RED under, ideally a user account which cannot log-in as a regular user. The default "pi" user on Raspbian has passwordless sudo privileges; not the kind of thing you'd want for a service that is accessible over the network...
