### ISSUE TITLE
"TypeError: Failed to set address"

### ISSUE THREAD

**Issue by shuynh84** [nielsnl68/node-red-contrib-i2c#7]
I'm trying to detect data from an MPU6050 Accelerometer but keep getting that error using the i2c in node. I'm pretty new to the raspberry pi and i2c.

**Comment by nielsnl68** [comment]
Can you show me the code that you use.so I can try to reproduce?

**Comment by shuynh84** [comment]
I'm trying to get data directly from the raspberry pi accelerometer in order to graph the x, y, z forces. I've tried using the 68,104, 150, 1101000, 1101001 for the address but keep getting the same error. There's no code, I'm using the Raspberry Pi 3 and have the MPU 6050 Invensense connected directly to SCL, SDA, 3.3v and ground. Please Ignore the 80 and 503 payload. That is the current sensor and temperature payload. Again, I'm pretty new to this and not really sure what the prompt is asking for and unable to googled the answers :/ Thanks you

![capture1](https://cloud.githubusercontent.com/assets/26530890/24326080/8cfd1420-1174-11e7-9102-d93ef0f21327.JPG)
![capture2](https://cloud.githubusercontent.com/assets/26530890/24326081/8fa8c5de-1174-11e7-93f0-93439a775736.JPG)
![capture3](https://cloud.githubusercontent.com/assets/26530890/24326082/91ce7d04-1174-11e7-82ce-b4ad8e0dcf04.JPG)

**Comment by nielsnl68** [comment]
Can you please export the node-red script and attach it to this issue? That
makes testing just a bit easier.


Op 25 mrt. 2017 22:07 schreef "shuynh84" <notifications@github.com>:

I'm trying to get data directly from the raspberry pi accelerometer in
order to graph the x, y, z forces. I've tried using the 68,104, 150,
1101000, 1101001 for the address but keep getting the same error. Please
Ignore the 80 and 503 payload. That is the current sensor and temperature
payload. Again, I'm pretty new to this and not really sure what the prompt
is asking for and unable to googled the answers :/ Thanks you

[image: capture1]
<https://cloud.githubusercontent.com/assets/26530890/24326080/8cfd1420-1174-11e7-9102-d93ef0f21327.JPG>
[image: capture2]
<https://cloud.githubusercontent.com/assets/26530890/24326081/8fa8c5de-1174-11e7-93f0-93439a775736.JPG>
[image: capture3]
<https://cloud.githubusercontent.com/assets/26530890/24326082/91ce7d04-1174-11e7-82ce-b4ad8e0dcf04.JPG>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nielsnl68/node-contrib-i2c/issues/7#issuecomment-289239615>,
or mute the thread

**Comment by shuynh84** [comment]
[{"id":"5776282f.c93338","type":"tab","label":"Flow 2"},{"id":"2333ea86.ec6b96","type":"i2c in","z":"5776282f.c93338","name":"","i2cdevice":"fcc28d7b.d71da","address":"68","command":"","count":"1","x":525,"y":277,"wires":[["586b08a.c5be5f8"]]},{"id":"62c798e8.4ba3d8","type":"inject","z":"5776282f.c93338","name":"","topic":"","payload":"","payloadType":"date","repeat":"10","crontab":"","once":true,"x":250,"y":261,"wires":[["2333ea86.ec6b96"]]},{"id":"586b08a.c5be5f8","type":"debug","z":"5776282f.c93338","name":"","active":true,"console":"false","complete":"false","x":777,"y":254,"wires":[]},{"id":"fcc28d7b.d71da","type":"i2c-device","z":"","device":"/dev/I2C-1","address":"68"}]

**Comment by nielsnl68** [comment]
Perfect i check it tomorrow.


Op 25 mrt. 2017 22:21 schreef "shuynh84" <notifications@github.com>:

**Comment by shuynh84** [comment]
thanks again

**Comment by nielsnl68** [comment]
Altrough i was not able to reproduce the issue; I made some small changes to the main js file.
Would you mind copy/paste the 26-i2c.js file to your i2c directory and tell of this fixes your issue. And restart node-red.

On an other note, I was wondering how you was planning to initialize mpu6050? Based on de arduino code it is a lot of commands that needs to be send. 

PS. The right  i2c address for the mpu6050 is 104.

**Comment by shuynh84** [comment]
I'm at work at the moment, will try when I get home. Sorry, I'm pretty new to these stuff. How do I go about putting that file in the i2c directory. Can i use the raspi explorer? or does it have to be done through sudo command?

What do you mean by initialize mpu6050? I thought the node is able to read the values and output the readings. Again, I'm pretty new to this scenario, I was looking for a node to read values from mpu6050 and was going to use the data to graph.

Although I'm using the raspberry pi. Would you happen to have a guide on how to do it on the arduino? Maybe I can convert the codes somehow. Thanks

**Comment by nielsnl68** [comment]
Op 27 mrt. 2017 15:06 schreef "shuynh84" <notifications@github.com>:

I'm at work at the moment, will try when I get home. Sorry, I'm pretty new
to these stuff. How do I go about putting that file in the i2c directory.
Can i use the raspi explorer? or does it have to be done through sudo
command?


Yes you can do it that way. You do not need sudo for this.

What do you mean by initialize mpu6050? I thought the node is able to read
the values and output the readings. Again, I'm pretty new to this scenario,
I was looking for a node to read values from mpu6050 and was going to use
the data to graph.

From what i have seen it need a lot of initialisation code to send to the
device.

Although I'm using the raspberry pi. Would you happen to have a guide on
how to do it on the arduino? Maybe I can convert the codes somehow. Thanks

Sorry, you are on your own here. I have no real knowledge on using the
mpu6050 i have not use the device myself other then just testing this issue.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nielsnl68/node-contrib-i2c/issues/7#issuecomment-289447477>,
or mute the thread

**Comment by shuynh84** [comment]
I'm still getting the same issue. For the i2c in node, what is command and returning length? 

This may be a dumb question, but when thrown out into the debug tab for node red. what is actually being display? is it data from the sensor? or will i need some kind of code to convert and get the accelerator data to display. I'm not really sending any data to it. I'm only trying to get data from the sensor and graph it.

**Comment by nielsnl68** [comment]
I am sorry to hear you have still the issues.
Do you have any other i2c device that you can uses to learn about how i2c
works. I did it by having an arduino connected to the pi and sending the
receiving data trough the serial port etc.
I just think the mpu6050 is just a step to much to for a starter.

I hope this gives you more inside where this error is comming from.

Btw you did restart node-red are you?

Op 28 mrt. 2017 00:56 schreef "shuynh84" <notifications@github.com>:

**Comment by nielsnl68** [comment]
I have upgrade my node modules. please check of your issue still exist.
